[[themes]]
name = "matugen"
[themes.palette]
foreground = "#efdfe1"
black = "#000000"
red = "#ffd2cc"
green = "#ffd4b1"
yellow = "#fad2db"
blue = "#ffd0db"
magenta = "#b38861"
cyan = "#aa8890"
white = "#514346"
bright_black = "#c0adb1"
bright_red = "#ff5449"
bright_green = "#ffdcc0"
bright_yellow = "#ffd9e1"
bright_blue = "#ffd9e1"
bright_magenta = "#eebd93"
bright_cyan = "#e3bdc5"
bright_white = "#191113"
