[[themes]]
name = "matugen"
[themes.palette]
foreground = "#f1dedc"
black = "#000000"
red = "#ffd2cc"
green = "#f6d9a0"
yellow = "#fed2cd"
blue = "#ffd2cc"
magenta = "#a78e5b"
cyan = "#ae8883"
white = "#534341"
bright_black = "#c2adaa"
bright_red = "#ff5449"
bright_green = "#fddfa6"
bright_yellow = "#ffdad5"
bright_blue = "#ffdad5"
bright_magenta = "#dfc38c"
bright_cyan = "#e7bdb7"
bright_white = "#1a1110"
