[[themes]]
name = "matugen"
[themes.palette]
foreground = "#f1dedd"
black = "#000000"
red = "#ffd2cc"
green = "#f9d8a0"
yellow = "#fed2cf"
blue = "#ffd2ce"
magenta = "#a98d5b"
cyan = "#ad8885"
white = "#534342"
bright_black = "#c2adab"
bright_red = "#ff5449"
bright_green = "#ffdea7"
bright_yellow = "#ffdad7"
bright_blue = "#ffdad7"
bright_magenta = "#e2c28c"
bright_cyan = "#e7bdb9"
bright_white = "#1a1111"
