[[themes]]
name = "matugen"
[themes.palette]
foreground = "{{colors.on_background.default.hex}}"
black = "{{colors.shadow.default.hex}}"
red = "{{colors.error.default.hex}}"
green = "{{colors.tertiary.default.hex}}"
yellow = "{{colors.secondary.default.hex}}"
blue = "{{colors.primary.default.hex}}"
magenta = "{{colors.tertiary_container.default.hex}}"
cyan = "{{colors.secondary_container.default.hex}}"
white = "{{colors.surface_variant.default.hex}}"
bright_black = "{{colors.outline.default.hex}}"
bright_red = "{{colors.error_container.default.hex}}"
bright_green = "{{colors.tertiary_fixed.default.hex}}"
bright_yellow = "{{colors.secondary_fixed.default.hex}}"
bright_blue = "{{colors.primary_fixed.default.hex}}"
bright_magenta = "{{colors.tertiary_fixed_dim.default.hex}}"
bright_cyan = "{{colors.secondary_fixed_dim.default.hex}}"
bright_white = "{{colors.surface.default.hex}}"
